### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by rontav** [grantholle/moviedb-promise#1]
Firstly, I would like to congratulate you on taking initiative for this project. 👍 

I like the switch to Promises, but I'm wondering why you didn't go all the way and use async/await.

Also, I think that the examples in the readme should be using async/await so that they are simpler.

**Comment by rontav** [comment]
I forgot to mention: I would love to help out if I can.

**Comment by grantholle** [comment]
Yeah, I've only recently started using async/await in a few things, so my familiarity with them is slowly increasing.

Making the switch wouldn't require too much refactoring. Thanks for the suggestion.

**Comment by grantholle** [comment]
I've pushed up my changes where internally uses some `async/await`.

I don't think all the examples in the readme need to be changed. While using async functions is nice, it's a little cumbersome in my opinion. The examples in the readme could be run exactly as they are. 

For example, if someone slapped this into a file to run,

```js
const res = await moviedb.searchMovie({ query: 'alien' })
console.log(res)
```

it would fail because it's not inside of an async function. Also, it's foundational to understand Promises before understanding async/await.

I've included an example of how to use async/await, but don't think it's necessary to change all the examples.
