### ISSUE TITLE
Missing return types and RequestParams is not suitable for many methods

### ISSUE THREAD

**Issue by lucafaggianelli** [grantholle/moviedb-promise#30]
I just saw that you ported the lib to TS... that's amazing, as I'm porting my app as well!

I have some issues with functions params and return types:

* `searchX` returns `any` and accepts `RequestParams` as input but it's missing `year`, `query` options

Actually, RequestParams seems to be used in many methods, also in `tvEpisodeInfo()`, where I would expect `seasonNumber` and `episodeNumber`.

**Comment by grantholle** [comment]
Yeah... so tmdb has great documentation with types and url params. The problem is that there are _so many_ functions. Adding each correct type with request parameters would be possible, just really time consuming to add each function's parameter type.

The functions get generated at runtime by getting added to the class prototype, but there isn't the ability to do types dynamically. I have written a simple script that generates the interface to include those dynamic functions. It may be possible to to generate those as well. I'll have to let it stew in my mind on how to accomplish it with the least amount of work 😉. I agree it would make using the package way better!

**Comment by lucafaggianelli** [comment]
Yeah, that's true! there are too many functions in the API!
If you need some help, I'm available, in the meantime I'll think too about a shortcut...

**Comment by lucafaggianelli** [comment]
by the way, I think that some methods must be fixed, for example I don't know how to call `searchMovie()`:
```ts
  const response = await client.searchMovie({ query: title, year })
```

It gives error as it expects: `'string | number | RequestParams'`

**Comment by grantholle** [comment]
Ok, yeah this needs to be rethought a little. I'm still kind of a beginner in typescript so I may need to do some more digging

**Comment by grantholle** [comment]
I have a #31 started to add type support for everything. I will merge it soon.

**Comment by lucafaggianelli** [comment]
That's great!

**Comment by grantholle** [comment]
`v3` is published. There's other breaking api changes for functions, which is why it's version 3 now.

**Comment by lucafaggianelli** [comment]
That's a huge and wonderful work! Though I'm sorry to say that I can't make it working... the `MovieDB` instance only has `baseUrl`, `requestToken`, `retrieveSession` and `sessionId`. This is weird, as the code is there, but seems not visible outside the package.

BTW, this is my code:
```ts
import { MovieDb } from 'moviedb-promise'
const client = new MovieDb(config.tmdbApiKey)
```

**Comment by grantholle** [comment]
Check out the [playground](https://github.com/grantholle/moviedb-promise-playground) I made and see if you don't get different results. It should have the type support working in that one.

**Comment by lucafaggianelli** [comment]
OK, I restarted the IDE and it works, probably just some IDE issues. Just testing it now

**Comment by grantholle** [comment]
Yeah I'm not sure what triggers Code to reanalyze dependencies either. I pretty much have to reload the window each time if things seem weird
