### ISSUE TITLE
TypeError: axios_1.default.request is not a function

### ISSUE THREAD

**Issue by dgrimaliuc-crunchyroll** [grantholle/moviedb-promise#83]
Not sure why but your library unfortunately doesn't works in my React project.
Seems like the request method from axios is undefined.

**Comment by dgrimaliuc-crunchyroll** [comment]
@grantholle could you please make a change and deploy it?

**Comment by grantholle** [comment]
What's the error specifically? Are you already using Axios in your project?

**Comment by dgrimaliuc-crunchyroll** [comment]
I don't use axios in my project.
Here is the error message:

<img width="443" alt="image" src="https://github.com/grantholle/moviedb-promise/assets/94832020/569a0f3f-fe53-4b5c-95c5-5f34a45790c1">

**Comment by grantholle** [comment]
I've created a [Remix project](https://github.com/grantholle/moviedb-react) and it works just fine for me (after including your api key).

Speaking of which, since this deals with sensitive data (your api key), you shouldn't be using it in the frontend. It's best used as a Node package used in your backend. It's not really intended to be used as a frontend-only package.
